// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg8WGboEMa9bXUanFI0sEe5ct9niJVlcU',
    appId: '1:710455746909:web:5647a9a98b1ea6680f48b4',
    messagingSenderId: '710455746909',
    projectId: 'health-tracker-d0990',
    authDomain: 'health-tracker-d0990.firebaseapp.com',
    storageBucket: 'health-tracker-d0990.appspot.com',
    measurementId: 'G-MM9SPHH1TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUmeI17BDB7SLga4F49aibPeRvI_uHEh0',
    appId: '1:710455746909:android:f006b26fda8b3ba00f48b4',
    messagingSenderId: '710455746909',
    projectId: 'health-tracker-d0990',
    storageBucket: 'health-tracker-d0990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDtw5mnHHUKzr3h11Olbp8RqRP9EnJrh0',
    appId: '1:710455746909:ios:0d92a3b3717434d30f48b4',
    messagingSenderId: '710455746909',
    projectId: 'health-tracker-d0990',
    storageBucket: 'health-tracker-d0990.appspot.com',
    iosBundleId: 'com.example.healthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDtw5mnHHUKzr3h11Olbp8RqRP9EnJrh0',
    appId: '1:710455746909:ios:d579a51bac2af3770f48b4',
    messagingSenderId: '710455746909',
    projectId: 'health-tracker-d0990',
    storageBucket: 'health-tracker-d0990.appspot.com',
    iosBundleId: 'com.example.healthTracker.RunnerTests',
  );
}
